### ISSUE TITLE
Implement wellbeing routines

### ISSUE THREAD

**Issue by janthonysantana** [dhrumilp12/Mental-Health-Companion#14]
29. Users will be able to opt into routines, which will involve various exercises for their mental wellbeing.
    29.a Mindfulness exercises will be an option in Routines.
    29.b Meditation exercises will be an option in Routines.
    29.c Stress Relief exercises will be an option in Routines.

**Comment by dhrumilp12** [comment]
used: YouTube Data API v3, Custom Search Engine and Custom Search API.
