### ISSUE TITLE
The chatbot must be able to identify more serious ideation (e.g. self-harm), and redirect the patient to more appropriate resources.

### ISSUE THREAD

**Issue by janthonysantana** [dhrumilp12/Mental-Health-Companion#22]

**Comment by dhrumilp12** [comment]
![image](https://github.com/user-attachments/assets/8527e9e3-abf7-4ec0-a726-ee92d1e1251f)
![image](https://github.com/user-attachments/assets/8527e9e3-abf7-4ec0-a726-ee92d1e1251f)
